general:
    GLOBAL_ATTRS: [projection, dx, dy, known_x, known_y, known_lat, known_lon, stdlon, truelat1, truelat2, filename_digits]
    COMBINED_PARAMS: [[tile_z_start, tile_z_end], [category_min, category_max]]

index_defaults:
    signed: "no"
    known_x: 1
    known_y: 1
    tile_bdr: 0
    scale_factor: 1
    row_order: "bottom_top"
    endian: "big"
    iswater: 16
    isice: 24
    isurban: 1
    isoilwater: 14
    mminlu: "USGS"
    filename_digits: 5
