general:
    VARIABLE_ATTRS: [description, type, category_min, category_max, units, missing_value, isoilwater, isice, isurban, islake, iswater, mminlu]
    DIMS_AVAIL: [x, y]

index_defaults:
    signed: no
    known_x: 1
    known_y: 1
    tile_bdr: 0
    scale_factor: 1
    row_order: bottom_top
    endian: big
    iswater: 16
    isice: 24
    isurban: 1
    isoilwater: 14
    mminlu: "USGS"
    filename_digits: 5
