name: CI
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 0 * * *' # Daily “At 00:00”
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: python-${{ matrix.python-version }}
    if: github.repository == 'lpilz/wps_xr'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v4
      - name: Set up conda environment
        uses: mamba-org/setup-micromamba@v1
        id: conda
        with:
          environment-file: ci/environment.yml
          init-shell: >-
            bash
          cache-environment: true
          cache-downloads: true
          post-cleanup: 'all'
          create-args: >-
            python=${{ matrix.python-version }}

      - name: Install wps_xr
        id: install
        run: |
          poetry install
      - name: Run Tests
        id: test
        run: |
          poetry run pytest --cov=wps_xr --cov-report xml tests/ ||
          poetry run pytest --cov=wps_xr --cov-report xml tests/
      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v4.6.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: false
      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@master
